### ISSUE TITLE
#12 (旅行计划) 旅行计划中休息和餐饮部分的跳转逻辑

### ISSUE THREAD

**Issue by Zera-Algorithm** [TRA-project/TRA#54]
点击休息，跳转到游玩完毕景点附近的酒店列表；点击餐饮，跳转到游玩完毕景点附近的美食列表；如果规划的某个景点，则在该旅行计划项目（对应景点）的备注进行提示，告知用户需要自行准备午餐。

**Comment by Elucidator-xrb** [comment]
最新: #72
