### ISSUE TITLE
出行计划生成部分页面修改

### ISSUE THREAD

**Issue by Zera-Algorithm** [TRA-project/TRA#71]
* 加载景点的真实图片
* 卡片上加一个刷新按钮，生成同分类下一个新的计划
* 支持用户自行添加和修改景点
![image](https://github.com/TRA-project/TRA/assets/54487697/71d9dfad-39f9-4144-9279-8c54f64d5f89)

**Comment by Elucidator-xrb** [comment]
1. 已加载真实景点
2. 刷新按钮应该是针对“方案”而言，不是加在卡片上吧？（我理解的没差吧
3. 已完成景点修改，感觉已集成景点添加，不过后续再加（当前是点击后跳转，可另选0~3个新景点，相当于兼具增/删/改功能；但用户体验上有好些优化空间）

**Comment by Zera-Algorithm** [comment]
2. 是的，针对某个方案刷新一个计划

**Comment by Elucidator-xrb** [comment]
关于2，后端好像没看到提供什么接口 @rain1732 

![image](https://github.com/TRA-project/TRA/assets/70893377/ecc06dfb-73b6-4eb8-a289-312c906b15bc)

难不成是POST /plan/new这个接口再用一遍然后截取3个计划之一重填？那意义何在（之前似乎有说过什么，我忘了）
