### ISSUE TITLE
出行计划详情部分修改

### ISSUE THREAD

**Issue by Zera-Algorithm** [TRA-project/TRA#72]
* 景点之间加入睡觉、吃饭等休息计划，可以点击更改时长和时间
   注：目前是只有睡觉的项目，需要支持修改睡觉的起始和终止时间
* 点击睡觉、吃饭等项目，跳转到旅行计划辅助页面，查看该项目对应上一个游玩结束景点附近的美食和酒店
   注：与zrp对接
![image](https://github.com/TRA-project/TRA/assets/54487697/462a09f4-295b-4642-925f-53660ca23236)

**Comment by Elucidator-xrb** [comment]
请 @rain1732 尽快修改后端接口：apifox上“获取旅行计划详情”的接口有诸多不适，我进行了修改，预览如下，你看如何

![image](https://github.com/TRA-project/TRA/assets/70893377/6a679f01-4bc1-45f9-a156-01a716f83e2a)

**Comment by rain1732** [comment]
已修改

**Comment by Zera-Algorithm** [comment]
辅助页面给我传一个scenery_id就可以，页面还是原来的那个名字(travelHotelRestaurant)，内容进行了调整

**Comment by Zera-Algorithm** [comment]
合一下我的PR

**Comment by rain1732** [comment]
（1）关于休息的修改，目前确实是全天范围内可任意修改，需要加入限制么
（2）关于更新请求，目前已经加入，详见apifox
（3）统一使用时间戳，双方均方便处理
