### ISSUE TITLE
出行计划生成页选择省市县区的修改

### ISSUE THREAD

**Issue by Zera-Algorithm** [TRA-project/TRA#73]
修复目标地区adcode与后端景点表不对应的问题

**Comment by Elucidator-xrb** [comment]
数据能爬到什么地步？全国范围的肯定没法手动改

所以需要定一下爬了哪些地区？而且根源上应该让后端提供一份它所用的adcode.json才对

**Comment by Elucidator-xrb** [comment]
不对不对，不是说已经会将adcode加入数据库了吗？那我向后端传adcode就行了（之前好像讨论过了吧）

（目前前端是向后端传一个 城市名字符串 的）

**Comment by Zera-Algorithm** [comment]
utility_address表：
![image](https://github.com/TRA-project/TRA/assets/54487697/94dc3b60-8d8d-4e69-b1b4-5791152a6d60)
目前可以用city_position_id（应该是吧）筛选相应城市的景点
